/** Declaration file generated by dts-gen */

export = PhraseappLoader;

declare class PhraseappLoader {
    constructor(options: any);

    configure(options: any): void;

    download(callback: Function): void;

    fetchTranslationFile(locale: string, callback: Function): void;

    downloadTranslationFile(locale: string, callback: Function): void;

    fetchLocales(callback: Function): void;
}

declare module 'phraseapp-loader' {
    export = PhraseappLoader;
}

